"""Init schema hyperliquid_vaults_discovery

Revision ID: a5aaa2b59ad0
Revises: 
Create Date: 2025-12-29 09:03:10.892124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5aaa2b59ad0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS hyperliquid_vaults_discovery")
    op.create_table('vaults',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vault_address', sa.String(length=42), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('leader_address', sa.String(length=42), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hyperliquid_vaults_discovery'
    )
    op.create_index(op.f('ix_hyperliquid_vaults_discovery_vaults_vault_address'), 'vaults', ['vault_address'], unique=True, schema='hyperliquid_vaults_discovery')
    op.create_table('vault_metrics',
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('vault_address', sa.String(length=42), nullable=False),
    sa.Column('tvl_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('apr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['vault_address'], ['hyperliquid_vaults_discovery.vaults.vault_address'], ),
    sa.PrimaryKeyConstraint('time', 'vault_address'),
    schema='hyperliquid_vaults_discovery'
    )
    op.drop_table('vault_metrics')
    op.drop_index(op.f('ix_vaults_vault_address'), table_name='vaults')
    op.drop_table('vaults')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('vaults',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('vault_address', sa.VARCHAR(length=42), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('leader_address', sa.VARCHAR(length=42), autoincrement=False, nullable=True),
    sa.Column('is_closed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vaults_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_vaults_vault_address'), 'vaults', ['vault_address'], unique=True)
    op.create_table('vault_metrics',
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('vault_address', sa.VARCHAR(length=42), autoincrement=False, nullable=False),
    sa.Column('tvl_usd', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('apr', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vault_address'], ['vaults.vault_address'], name=op.f('vault_metrics_vault_address_fkey')),
    sa.PrimaryKeyConstraint('time', 'vault_address', name=op.f('vault_metrics_pkey'))
    )
    op.drop_table('vault_metrics', schema='hyperliquid_vaults_discovery')
    op.drop_index(op.f('ix_hyperliquid_vaults_discovery_vaults_vault_address'), table_name='vaults', schema='hyperliquid_vaults_discovery')
    op.drop_table('vaults', schema='hyperliquid_vaults_discovery')

    op.execute("DROP SCHEMA IF EXISTS hyperliquid_vaults_discovery CASCADE")
    # ### end Alembic commands ###
