"""add risk params and borrow metrics

Revision ID: e8d4afffd4ec
Revises: f6widenevmapy
Create Date: 2026-01-08 03:17:26.626041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8d4afffd4ec'
down_revision: Union[str, None] = 'f6widenevmapy'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evm_pool_metrics', sa.Column('total_debt_usd', sa.Numeric(precision=20, scale=2), nullable=True), schema='hyperliquid_vaults_discovery')
    op.add_column('evm_pool_metrics', sa.Column('utilization_rate', sa.Numeric(precision=10, scale=6), nullable=True), schema='hyperliquid_vaults_discovery')
    op.add_column('evm_pool_metrics', sa.Column('apy_borrow_variable', sa.Numeric(precision=10, scale=6), nullable=True), schema='hyperliquid_vaults_discovery')
    op.add_column('evm_pool_metrics', sa.Column('apy_borrow_stable', sa.Numeric(precision=10, scale=6), nullable=True), schema='hyperliquid_vaults_discovery')
    op.add_column('evm_pools', sa.Column('ltv', sa.Numeric(precision=10, scale=4), nullable=True), schema='hyperliquid_vaults_discovery')
    op.add_column('evm_pools', sa.Column('liquidation_threshold', sa.Numeric(precision=10, scale=4), nullable=True), schema='hyperliquid_vaults_discovery')
    op.add_column('evm_pools', sa.Column('liquidation_bonus', sa.Numeric(precision=10, scale=4), nullable=True), schema='hyperliquid_vaults_discovery')
    op.add_column('evm_pools', sa.Column('reserve_factor', sa.Numeric(precision=10, scale=4), nullable=True), schema='hyperliquid_vaults_discovery')
    op.add_column('evm_pools', sa.Column('decimals', sa.Integer(), nullable=True), schema='hyperliquid_vaults_discovery')
    op.add_column('evm_pools', sa.Column('source', sa.String(length=50), nullable=True), schema='hyperliquid_vaults_discovery')
    op.drop_index(op.f('ix_top_500_vaults_rank'), table_name='top_500_vaults', schema='hyperliquid_vaults_discovery')
    op.create_index(op.f('ix_hyperliquid_vaults_discovery_top_500_vaults_rank'), 'top_500_vaults', ['rank'], unique=False, schema='hyperliquid_vaults_discovery')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hyperliquid_vaults_discovery_top_500_vaults_rank'), table_name='top_500_vaults', schema='hyperliquid_vaults_discovery')
    op.create_index(op.f('ix_top_500_vaults_rank'), 'top_500_vaults', ['rank'], unique=False, schema='hyperliquid_vaults_discovery')
    op.drop_column('evm_pools', 'source', schema='hyperliquid_vaults_discovery')
    op.drop_column('evm_pools', 'decimals', schema='hyperliquid_vaults_discovery')
    op.drop_column('evm_pools', 'reserve_factor', schema='hyperliquid_vaults_discovery')
    op.drop_column('evm_pools', 'liquidation_bonus', schema='hyperliquid_vaults_discovery')
    op.drop_column('evm_pools', 'liquidation_threshold', schema='hyperliquid_vaults_discovery')
    op.drop_column('evm_pools', 'ltv', schema='hyperliquid_vaults_discovery')
    op.drop_column('evm_pool_metrics', 'apy_borrow_stable', schema='hyperliquid_vaults_discovery')
    op.drop_column('evm_pool_metrics', 'apy_borrow_variable', schema='hyperliquid_vaults_discovery')
    op.drop_column('evm_pool_metrics', 'utilization_rate', schema='hyperliquid_vaults_discovery')
    op.drop_column('evm_pool_metrics', 'total_debt_usd', schema='hyperliquid_vaults_discovery')
    # ### end Alembic commands ###
